---
# template source: https://github.com/bretfisher/super-linter-workflow/blob/main/templates/call-super-linter.yaml
name: Lint Code Base

on:
  push:
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
    branches:
      - 'main'
      - 'feature/*'
    tags:
      - '[0-9]+.[0-9]+-[0-9]+'
  pull_request:

jobs:
  call-super-linter:

    name: Call Super-Linter
    
    permissions:
      contents: read # clone the repo to lint
      statuses: write #read/write to repo custom statuses

    ### use Reusable Workflows to call my workflow remotely
    ### https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
    ### you can also call workflows from inside the same repo via file path

    uses: ./.github/workflows/reusable-super-linter.yaml
    
    ### Optional settings examples
    
    # with:
      ### For a DevOps-focused repository. Prevents some code-language linters from running
      ### defaults to false
      # devops-only: false
      
      ### A regex to exclude files from linting
      ### defaults to empty
      # filter-regex-exclude: html/.*
